# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumposts', '0002_auto_20170511_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='post_link',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
