# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumposts', '0003_forumpost_post_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='post_link',
            field=models.URLField(default=''),
        ),
    ]
