# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-29 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumposts', '0010_auto_20170929_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
