# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-30 01:05
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forumposts', '0012_auto_20170929_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
