# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-04 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forumposts', '0013_auto_20170929_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Comment for a particular forum post', max_length=10000)),
                ('date_time', models.DateTimeField(default=None, null=True)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forumposts.ForumPost')),
            ],
        ),
    ]
