# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-08 00:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forumposts', '0015_auto_20171004_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forumpost',
            old_name='post_id',
            new_name='id',
        ),
    ]
